// Package config reads and validates autosolve inputs from environment variables.
package config

import (
	"fmt"
	"os"
	"strconv"
	"strings"
)

const (
	defaultCommitSignature = "Co-Authored-By: Claude <noreply@anthropic.com>"
	defaultBranchPrefix    = "autosolve/"
	defaultPRFooter        = "---\n\n*This PR was auto-generated by [claude-autosolve-action](https://github.com/cockroachdb/actions) using Claude Code.*\n*Please review carefully before approving.*"
)

// Config holds validated configuration for an autosolve run.
type Config struct {
	// Task inputs
	SystemPrompt       string
	Skill              string
	ContextVars        []string // env var names to pass through to Claude
	AssessmentCriteria string
	Model              string
	BlockedPaths       []string
	FooterType         string // "assessment" or "implementation"

	// Implementation-specific
	MaxRetries   int
	AllowedTools string
	CreatePR     bool

	// PR creation
	ForkOwner        string
	ForkRepo         string
	ForkPushToken    string
	PRCreateToken    string
	PRBaseBranch     string
	PRLabels         string
	PRDraft          bool
	PullRequestTitle string
	PRBodyTemplate   string
	PRFooter         string
	GitUserName      string
	GitUserEmail     string
	BranchPrefix     string
	BranchSuffix     string
	CommitSignature  string

	// GitHub context
	GithubRepository string
}

// LoadAssessConfig reads config for the assess subcommand.
func LoadAssessConfig() (*Config, error) {
	c := &Config{
		SystemPrompt:       os.Getenv("INPUT_SYSTEM_PROMPT"),
		Skill:              os.Getenv("INPUT_SKILL"),
		ContextVars:        parseContextVars(os.Getenv("INPUT_CONTEXT_VARS")),
		AssessmentCriteria: os.Getenv("INPUT_ASSESSMENT_CRITERIA"),
		Model:              os.Getenv("INPUT_MODEL"),
		BlockedPaths:       ParseBlockedPaths(os.Getenv("INPUT_BLOCKED_PATHS")),
		FooterType:         "assessment",

		GithubRepository: os.Getenv("GITHUB_REPOSITORY"),
	}
	if err := c.validateTask(); err != nil {
		return nil, err
	}
	return c, nil
}

// LoadImplementConfig reads config for the implement subcommand.
func LoadImplementConfig() (*Config, error) {
	createPR, err := envBool("INPUT_CREATE_PR", true)
	if err != nil {
		return nil, err
	}
	prDraft, err := envBool("INPUT_PR_DRAFT", true)
	if err != nil {
		return nil, err
	}

	c := &Config{
		SystemPrompt:     os.Getenv("INPUT_SYSTEM_PROMPT"),
		Skill:            os.Getenv("INPUT_SKILL"),
		ContextVars:      parseContextVars(os.Getenv("INPUT_CONTEXT_VARS")),
		Model:            os.Getenv("INPUT_MODEL"),
		BlockedPaths:     ParseBlockedPaths(os.Getenv("INPUT_BLOCKED_PATHS")),
		FooterType:       "implementation",
		MaxRetries:       envOrDefaultInt("INPUT_MAX_RETRIES", 3),
		AllowedTools:     envOrDefault("INPUT_ALLOWED_TOOLS", "Read,Write,Edit,Grep,Glob,Bash(git add:*),Bash(git status:*),Bash(git diff:*),Bash(git log:*),Bash(git show:*),Bash(go build:*),Bash(go test:*),Bash(go vet:*),Bash(make:*)"),
		CreatePR:         createPR,
		ForkOwner:        os.Getenv("INPUT_FORK_OWNER"),
		ForkRepo:         os.Getenv("INPUT_FORK_REPO"),
		ForkPushToken:    os.Getenv("INPUT_FORK_PUSH_TOKEN"),
		PRCreateToken:    os.Getenv("INPUT_PR_CREATE_TOKEN"),
		PRBaseBranch:     os.Getenv("INPUT_PR_BASE_BRANCH"),
		PRLabels:         envOrDefault("INPUT_PR_LABELS", "autosolve"),
		PRDraft:          prDraft,
		PullRequestTitle: os.Getenv("INPUT_PR_TITLE"),
		PRBodyTemplate:   os.Getenv("INPUT_PR_BODY_TEMPLATE"),
		PRFooter:         envOrDefault("INPUT_PR_FOOTER", defaultPRFooter),
		GitUserName:      envOrDefault("INPUT_GIT_USER_NAME", "autosolve[bot]"),
		GitUserEmail:     envOrDefault("INPUT_GIT_USER_EMAIL", "autosolve[bot]@users.noreply.github.com"),
		BranchPrefix:     envOrDefault("INPUT_BRANCH_PREFIX", defaultBranchPrefix),
		BranchSuffix:     os.Getenv("INPUT_BRANCH_SUFFIX"),
		CommitSignature:  envOrDefault("INPUT_COMMIT_SIGNATURE", defaultCommitSignature),

		GithubRepository: os.Getenv("GITHUB_REPOSITORY"),
	}
	if err := c.validateTask(); err != nil {
		return nil, err
	}
	if err := c.validatePR(); err != nil {
		return nil, err
	}

	// Remove tokens from the environment so they are not inherited by
	// child processes (e.g. Claude CLI). The values are already captured
	// in the Config struct.
	os.Unsetenv("INPUT_FORK_PUSH_TOKEN")
	os.Unsetenv("INPUT_PR_CREATE_TOKEN")

	return c, nil
}

// LoadSecurityConfig reads config for the security subcommand.
func LoadSecurityConfig() (*Config, error) {
	return &Config{
		BlockedPaths: ParseBlockedPaths(os.Getenv("INPUT_BLOCKED_PATHS")),
	}, nil
}

func (c *Config) validateTask() error {
	if c.SystemPrompt == "" && c.Skill == "" {
		return fmt.Errorf("at least one of 'system_prompt' or 'skill' must be provided")
	}
	if c.Model == "" {
		return fmt.Errorf("'model' must be provided")
	}
	return nil
}

func (c *Config) validatePR() error {
	if !c.CreatePR {
		return nil
	}
	var missing []string
	if c.ForkOwner == "" {
		missing = append(missing, "fork_owner")
	}
	if c.ForkRepo == "" {
		missing = append(missing, "fork_repo")
	}
	if c.ForkPushToken == "" {
		missing = append(missing, "fork_push_token")
	}
	if c.PRCreateToken == "" {
		missing = append(missing, "pr_create_token")
	}
	if os.Getenv("SCRIPTS_DIR") == "" {
		missing = append(missing, "SCRIPTS_DIR")
	}
	if len(missing) > 0 {
		return fmt.Errorf("when create_pr is true, the following inputs are required: %s", strings.Join(missing, ", "))
	}
	return nil
}

// ValidateAuth checks that Vertex AI authentication is configured.
func ValidateAuth() error {
	if os.Getenv("CLAUDE_CODE_USE_VERTEX") != "1" {
		return fmt.Errorf("CLAUDE_CODE_USE_VERTEX must be set to '1'")
	}
	var missing []string
	if os.Getenv("ANTHROPIC_VERTEX_PROJECT_ID") == "" {
		missing = append(missing, "ANTHROPIC_VERTEX_PROJECT_ID")
	}
	if os.Getenv("CLOUD_ML_REGION") == "" {
		missing = append(missing, "CLOUD_ML_REGION")
	}
	if len(missing) > 0 {
		return fmt.Errorf("Vertex AI auth requires: %s", strings.Join(missing, ", "))
	}
	return nil
}

// ParseBlockedPaths splits a comma-separated blocked paths string into a slice.
// Returns the default blocked path if raw is empty.
func ParseBlockedPaths(raw string) []string {
	if raw == "" {
		return []string{".github/workflows/"}
	}
	var paths []string
	for _, p := range strings.Split(raw, ",") {
		p = strings.TrimSpace(p)
		if p != "" {
			paths = append(paths, p)
		}
	}
	return paths
}

// SecurityReviewModel returns a lightweight model suitable for the AI
// security review.
func (c *Config) SecurityReviewModel() string {
	return "claude-sonnet-4-6"
}

func envBool(key string, def bool) (bool, error) {
	v := strings.ToLower(os.Getenv(key))
	if v == "" {
		return def, nil
	}
	switch v {
	case "true":
		return true, nil
	case "false":
		return false, nil
	default:
		return false, fmt.Errorf("invalid boolean value for %s: %q (expected true or false)", key, os.Getenv(key))
	}
}

func parseContextVars(raw string) []string {
	if raw == "" {
		return nil
	}
	var result []string
	for _, s := range strings.Split(raw, ",") {
		s = strings.TrimSpace(s)
		if s != "" {
			result = append(result, s)
		}
	}
	return result
}

func envOrDefault(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}

func envOrDefaultInt(key string, def int) int {
	v := os.Getenv(key)
	if v == "" {
		return def
	}
	n, err := strconv.Atoi(v)
	if err != nil {
		return def
	}
	return n
}
